### PR TITLE
WIP: Contributor stats

### PR DESCRIPTION
**Pull request by larsoner**

### CODE REVIEW

**Comment by drammock** [comment]
@larsoner any idea why CircleCI not running on this PR?

**Comment by larsoner** [comment]
This is a PR in my fork, not surprised it doesn't run (some think I ever configured it to). I just opened it to have a convenient diff and plan to open a PR to MNE in the next couple of days. In the meantime you can do a local build though

**Comment by drammock** [comment]
> This is a PR in my fork, not surprised it doesn't run

ah oops, didn't notice that

**Comment by autofix-troubleshooter** [comment]
Hi! I'm the <a href="https://autofix.ci">autofix logo<strong>autofix.ci</strong></a> troubleshooter bot.

It looks like you correctly set up a CI job that uses the autofix.ci GitHub Action, but the [**autofix.ci GitHub App**](https://github.com/apps/autofix-ci/) has not been installed for this repository. This means that autofix.ci unfortunately does not have the permissions to fix this pull request. If you are the repository owner, please install the app and then restart the CI workflow! 😃

**Pull request closed without merging**
